### PR TITLE
Fix for masthead timing bug

### PR DESCRIPTION
**Pull request by beep**
Rather than doing a bunch of custom JS folderol, I’ve moved back to the `lib/collapsible.js` library. `navigation.js` and `search.js` could probably be combined, but for now, this should clear up #5.

### CODE REVIEW

**Comment by beep** [comment]
(@ryanpitts, b2adb13237a06db69fcea6374451fddfacf3030fb2adb13237a06db69fcea6374451fddfacf3030f has some minor markup edits to the template files. Do those look okay?)

**Comment by ryanpitts** [comment]
Yep, looks good to me 👍

**Comment by ryanpitts** [comment]
@beep I just pushed these changes to staging so you and @kissane won't be waiting on this Pacific Timer tomorrow morning. ([example link](https://opennews-source-staging.herokuapp.com/articles/low-budget-natural-language-processing/))

**Comment by kissane** [comment]
Looks awesome, thank you!

**Pull request merged**
