### PR TITLE
People list, icon fixes, tigers, bears, oh my!

### PR DESCRIPTION
**Pull request by beep**
Should help with #45, #50, and #61.

### CODE REVIEW

**Comment by ryanpitts** [comment]
@beep this looks great, can you bump the grunt process to catch this one up after I merged the other PR?

**Comment by beep** [comment]
@ryanpitts done!

**Comment by ryanpitts** [comment]
@beep seriously, thank you so much for repointing the grunt output to `/static/base/_v2`

**Comment by beep** [comment]
@ryanpitts it is the literal least i could do, sorry i didn’t start there!

**Pull request merged**
