### PR TITLE
Organizations list update #49

### PR DESCRIPTION
**Pull request by beep**
I’ve made `profile-person` a bit more generic (`.profile`, `.tmpl-article .profile`, and `.profile.profile-lead`), which should help with #49.

@ryanpitts I updated a few class references in the templates, but didn’t delete the promos block from `organization_list`—figured I’d let you do the honors. Everything else look okay, though?

### CODE REVIEW

**Comment by ryanpitts** [comment]
@beep can I talk you into regenerating the `main.css` inside `dist`? I think it's outdated here because of the other PR I just merged.

**Comment by ryanpitts** [comment]
sorry about the tango here involved in keeping `dist` in the repo, @beep! If we had a longer timeline, I'd certainly want to set aside a chunk of time to understand and set up the compile pipeline.

**Comment by beep** [comment]
@ryanpitts You certainly can! And I just did; things are ready to merge whenever you’re ready.

Two related questions:

1. Would it be easier for you if I built the `dist` files right into that `v2` directory?
2. Would it be easier for you if I worked directly on master, rather than in issue-specific branches?

I realize we’re coming into the home stretch, but if there’s something I could be doing differently to make things easier for you, let me know.

**Comment by beep** [comment]
> sorry about the tango here involved in keeping dist in the repo, @beep! If we had a longer timeline, I'd certainly want to set aside a chunk of time to understand and set up the compile pipeline.

oh jeez, no apology needed! i appreciate your patience with all the merge bits!

**Comment by ryanpitts** [comment]
@beep I would say

1. yeah! That would be awesome. My current process is to merge a PR, pull `master` down to local, copy updated files from `tmpl/dist` into that `_v2/dist`, then commit and push back to `master`. Streamlining that would be sweet.
2. I think feature branches are probably better, if only because our Heroku deploy pipeline watches `master` and rebuilds on every commit. If you're anything like me, you might prefer to be able to push lots of small commits without worry about breaking builds, which points toward feature branches. (That's how I'll plan to work after relaunch as well)

**Comment by beep** [comment]
1. Awesome! I’ll fire up an issue to move things over tomorrow. Thanks for letting me know! Saving you steps is what I am _all about._
2. Fantastic. I’ll keep on with the PR workflow, then. (And I’m a many-small-commits kinda person, too.)

Thanks for the feedback, @ryanpitts!

**Pull request merged**
